#!/bin/bash
# Ziel des Scripts
#	
#
#	created		- Ullrich Weichert
#	edit 		- 
#	last edit	- 22.06.2021
#	version		- 0.0
VERSION="0.0"
RELEASE="Aufmerksame Apostel analysieren afrikanische Apfelernten."

##	
#	Erklärung:
#	==========
	
#	Usage : SCRIPT 
##	

#### Pruefen ob das Script schon laeuft

pname="$(echo $0|sed 's@.*/@@')"
semname="${pname}.pid"
semfile="/tmp/${semname}"
if [ -f "${semfile}" ]; then
        pid="$(cat "${semfile}")"
        if [ -f "/proc/${pid}/stat" ]; then
                id="$(cat /proc/$$/stat|awk '{print $2}')"
                if [ -n "$(grep -P "\Q${id}\E" "/proc/${pid}/stat")" ]; then
                        echo "$(date): $pname is already running!"
                        exit 1
                fi
        fi
fi
echo $$ > "${semfile}"

#### Variablen

#### Functions
